export class Attendee {
    // id and register date are optional; generated by save action on server
    _id? : string;
    registerDate?: Date;
    formattedRegisterDate?: Date;
    firstName: string;
    lastName:string;
    address: string;
    address2: string;
    zipCode: string;
    city: string;
    state: string;
    country: string;
    name?: string
}
